apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: product-b
  namespace: flux-system
spec:
  interval: 5m
  path: product-b-config/deploy
  targetNamespace: product-b
  prune: true
  sourceRef:
    kind: GitRepository
    name: product-b
