apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: product-b
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dipti-pai/product-b
  ref:
    branch: main
