apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: product-a
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/org/product-a-config
  ref:
    branch: main
